# EMULATION PARAMETERS
EMULATION = 'Phoenix-ram-v0'

# TRAINING PARAMETERS
NUM_EPISODES = 1000
NUM_TIME_STEPS = 100

# REPLAY BUFFER PARAMETERS
REPLAY_BUFFER_CAPACITY = 1000
REPLAY_BUFFER_SAMPLING_SIZE = 32

# LEARNING RATE PARAMETER
LEARNING_RATE = 0.0002
