# EMULATION PARAMETERS
EMULATION = 'Assault-ram-v0'

# TRAINING PARAMETERS
NUM_EPOCHS = 20

# REPLAY BUFFER PARAMETERS
REPLAY_BUFFER_CAPACITY = 100000
REPLAY_BUFFER_SAMPLING_SIZE = 32

# LEARNING RATE PARAMETER
LEARNING_RATE = 0.0002
