# EMULATION PARAMETERS
EMULATION = 'SpaceInvaders-ram-v0'

# TRAINING PARAMETERS
NUM_EPOCHS = 5

# REPLAY BUFFER PARAMETERS
REPLAY_BUFFER_CAPACITY = 100000
REPLAY_BUFFER_SAMPLING_SIZE = 32

# LEARNING RATE PARAMETER
LEARNING_RATE = 0.0002

# FRAME PARAMETERS
FRAME_SKIP = 4

# EPSILON PARAMETERS
EPSILON_DECAY_RATE = 0.996
EPSILON_MIN = 0.1
DISCOUNT_FACTOR = 0.95

# DDQN PARAMETERS
TARGET_MODEL_UPDATE_ITERATIONS = 2
